# Analyse exploratoire
## Introduction

Nous rappelons que le but de la mission est d'dentifier les causes d'attrition au sein de TechNova Partners.
La responsable SIRH a fourni 3 principaux fichiers source que nous allons analyser, et sur lesquels nous allons nous appuyer pour notre étude.

On peut les trouver dans `assets/` : 
* extrait_eval.csv
* extrait_sirh.csv
* extrait_sondage.csv

## Import des modules

In [1]:
import pandas as pd

## Familiarisation avec les données
### Extrait SIRH
Le fichier est un extrait de la base de données du SIRH de TechNovaPartners. Il s'agit de la table principale des données anonymisées des employés de l'entreprise.

In [2]:
sirh = pd.read_csv("./assets/extrait_sirh.csv")
sirh.head()

,id_employee,age,genre,revenu_mensuel,statut_marital,departement,poste,nombre_experiences_precedentes,nombre_heures_travailless,annee_experience_totale,annees_dans_l_entreprise,annees_dans_le_poste_actuel
0,1,41,F,5993,Célibataire,Commercial,Cadre Commercial,8,80,8,6,4
1,2,49,M,5130,Marié(e),Consulting,Assistant de Direction,1,80,10,10,7
2,4,37,M,2090,Célibataire,Consulting,Consultant,6,80,7,0,0
3,5,33,F,2909,Marié(e),Consulting,Assistant de Direction,1,80,8,8,7
4,7,27,M,3468,Marié(e),Consulting,Consultant,9,80,6,2,2



On peut retenir au moins les colonnes suivantes :
 * `id_employee` : identifiant unique, peut servir à lier les tables entre elles
 * `age` : l'âge peut être intéressant pour dégager des tendances
 * `genre`
 * `revenu_mensuel`
 * `statut_marital`
 * `departement` : service dans lequel l'employé est affecté, donnée importante , peut permettre d'identifier des problèmes de process et/ou de management
 * `poste` : donnée importante qui peut permettre d'identifier des problèmes liés au poste, et/ou dont le poste peut être un facteur déterminant aux démissions
 * `nombre_experiences_precedentes`
 * `nombre_heures_travailless` : il semble que l'échantillon donné soit pour tous les individus de 80h travaillées, à analyser.
 * `annee_experience_totale`
 * `annees_dans_l_entreprise` : peut être déterminant, facteur de lassitude ou de besoin de nouvelles expériences
 * `annees_dans_le_poste_actuel` : également, facteur de lassitude, problématiques sur le poste

### Extrait Evaluation

In [3]:
evaluation = pd.read_csv("./assets/extrait_eval.csv")
evaluation.head()

,satisfaction_employee_environnement,note_evaluation_precedente,niveau_hierarchique_poste,satisfaction_employee_nature_travail,satisfaction_employee_equipe,satisfaction_employee_equilibre_pro_perso,eval_number,note_evaluation_actuelle,heure_supplementaires,augementation_salaire_precedente
0,2,3,2,4,1,1,E_1,3,Oui,11 %
1,3,2,2,2,4,3,E_2,4,Non,23 %
2,4,2,1,3,2,3,E_4,3,Oui,15 %
3,4,3,1,3,3,3,E_5,3,Oui,11 %
4,1,3,1,2,4,3,E_7,3,Non,12 %

### Extrait Sondage

In [4]:
sondage = pd.read_csv("./assets/extrait_sondage.csv")
sondage.head()

,a_quitte_l_entreprise,nombre_participation_pee,nb_formations_suivies,nombre_employee_sous_responsabilite,code_sondage,distance_domicile_travail,niveau_education,domaine_etude,ayant_enfants,frequence_deplacement,annees_depuis_la_derniere_promotion,annes_sous_responsable_actuel
0,Oui,0,0,1,1,1,2,Infra & Cloud,Y,Occasionnel,0,5
1,Non,1,3,1,2,8,1,Infra & Cloud,Y,Frequent,1,7
2,Oui,0,3,1,4,2,2,Autre,Y,Occasionnel,0,0
3,Non,0,3,1,5,3,4,Infra & Cloud,Y,Frequent,3,0
4,Non,1,3,1,7,2,1,Transformation Digitale,Y,Occasionnel,2,2